---
title: "Survival analysis"
author: "Salma Elshahawy"
date: "3/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Randomised trial of two treatment regimens for lung cancer. This is a standard survival analysis data set.
library(survival)
library(survminer)
library(tidyverse)
library(ggplot2)
library(plyr)
```

```{r}
data("veteran")
str(veteran)
```


We need to compare `celltype` change during time

```{r}
surv_object <- Surv(time = veteran$time, event = veteran$status)
surv_object 
```



```{r}
# Fit survival data using the Kaplan-Meier method
fit1 <- survfit(surv_object ~ celltype, data = veteran) 
summary(fit1)
```

You can examine the corresponding survival curve by passing the survival object to the ggsurvplot function. The pval = TRUE argument is very useful, because it plots the p-value of a log rank test as well!

```{r, fig.height = 4, fig.width = 5, fig.align = "center"}
ggsurvplot(fit1, pval = TRUE,
           fun = 'pct', 
           conf.int = TRUE, 
           surv.median.line = "hv", # Specify median survival
           risk.table = TRUE, # Add risk table
           ggtheme = theme_bw(), # Change ggplot2 theme
           data = veteran)
```

```{r}
summary(fit1)$table
```
```{r, fig.height = 4, fig.width = 5, fig.align = "center"}
ggsurvplot(fit1,
          risk.table.col = "strata", # Change risk table color by groups
          ggtheme = theme_bw(), # Change ggplot2 theme
          xlim = c(0, 250))
```

```{r}
ggsurvplot(fit1,
          conf.int = TRUE,
          risk.table.col = "strata", # Change risk table color by groups
          ggtheme = theme_bw(), # Change ggplot2 theme
          fun = "cumhaz")
```
```{r}
summary(fit1)
```



```{r}
res.sum <- surv_summary(fit1)
head(res.sum)
```

```{r}
attr(res.sum, "table")
surv_diff <- survdiff(Surv(time, status) ~ celltype, data = veteran)
surv_diff
```

```{r}
# Fit a Cox proportional hazards model
model <- coxph( Surv(time, status) ~ celltype + prior + karno + age,
                data = veteran )
summary(model)
ftest <- cox.zph(model)
ftest
ggcoxzph(ftest)
```


```{r}
ggsurvplot(survfit(model, data=vet), color = "#2E9FDF",
           ggtheme = theme_minimal())
```

```{r}
# veteran$age_gp <- ifelse(veteran$age > 60, ">60", "<=60")
fit <- coxph( Surv(time, status) ~ celltype+karno ,
                data = veteran )
fit
```

```{r}
ggforest(model)
```








